version: "3"

services:
  application:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.application
    container_name: epseed-app
    depends_on:
      - server
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app

  database:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.database
    container_name: epseed-db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    container_name: epseed-server
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
